language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
     secure: "WgthYsGcPHg+GYjGtwl5EBLMtaPh18YYNziBNEFWuKnsZQlWTWF8yX7ve822N2AcYiTWArSiDjerV7HQyeJmKEmcROZDquy4sG6AYdfEiFkRF7aTR61Xdr7uEfueSk8OFxDkOLu366qcghDYZp3HX/D9dubM5C3fYM7mcRR8Fxhh4B6z3st8RBrMXgo5B4Ny1Aq5TyJRmoApQ21Kgoyg96zszp8ix9htq/r9nCzSyFt7rDnDQ+h9eDR8c22sxo+WfgY6uJaBRxY6Efhl90REdDJifD8ovpSMMd34+iEvXWqR7INRiIxgnKuZ6J4IaENsiN/g5b2/ZC31ONAJqWu/bdj0FywMbUM8wGthvUI8wGKjMVJKfjV88FE4hG5ColgbwZB7n3jI3uBCmXo9hvd7hCi2vRg54A5NXrFrjGVo8706gyCWY7O73LvEubMoGjyX9bLqFXtFwnwENcGNyuaGhQsHPdub39iv9833beiGdPLrMArrx66NanbREIGeMh6q73RghCrrmQMU7SVFmbBa5LPrNTUZnGMxBURvMIdKu3x27q4JsoVvsmylSfuWzKanTg6jwga3glrtfTNoDpFn20p5ml1R1o6xednB3KRHWQKqBX8tnuT7xAzdB+rPRlogBk1TpYKZ/S0xLYrYJ4q4Dy9Z1eBJe+7aebPUauweDA8="
     app: adminreactbookstore